name: Reset Courts Every Day at 5 AM EDT
on:
  schedule:
    - cron: "0 9 * * *" # Runs once daily at 5 AM EDT (9 AM UTC)
  workflow_dispatch: # Allows manual triggering of the workflow for testing
jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Make HTTP request to reset courts
        run: |
          curl -X POST https://us-central1-brampton-tennis-queue.cloudfunctions.net/resetCourts \
            -H "Content-Type: application/json" \
            -d '{"password": "XYZ"}'
