name: Track Metrics Every 20 Minutes from 8 AM to 11 PM EDT
on:
  schedule:
    - cron: "0,20,40 12-23 * * *" # 8:00 AM - 7:40 PM EDT (12:00-23:40 UTC)
    - cron: "0,20,40 0-2 * * *" # 8:00 PM - 10:40 PM EDT (00:00-02:40 UTC next day)
    - cron: "0 3 * * *" # 11:00 PM EDT (03:00 UTC next day)
  workflow_dispatch: # Allows manual triggering of the workflow for testing
jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Make HTTP request to track metrics
        run: |
          curl -X POST https://us-central1-brampton-tennis-queue.cloudfunctions.net/trackMetrics
